version: "3.9"
services:
    db:
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
        volumes:
            - .:/myapp
        ports:
            - 3000:3000
        depends_on:
            - db
#    api:
#        build: ./api
#        command: npm start
#        volumes:
#            - ./api:/api
#            - /api/node_modules
#        networks:
#            - app-network
    nginx:
        image: nginx:latest
        volumes:
            # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
